// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-Dhgpv3MVr0-JZnBGblK1fSuOH15BnnQ',
    appId: '1:574109052855:web:9a73434fc57fd598910232',
    messagingSenderId: '574109052855',
    projectId: 'mypfe-9ed9e',
    authDomain: 'mypfe-9ed9e.firebaseapp.com',
    storageBucket: 'mypfe-9ed9e.appspot.com',
    measurementId: 'G-4JHQMRCD85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLAWUke3HNX_sDAyjck65-1cagsV6XkLs',
    appId: '1:574109052855:android:363ad0e0a1ce0b16910232',
    messagingSenderId: '574109052855',
    projectId: 'mypfe-9ed9e',
    storageBucket: 'mypfe-9ed9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcDBw9Lk7Zh_OZWYRIpHxMVRXeX2sZo_A',
    appId: '1:574109052855:ios:e83243ef255d920c910232',
    messagingSenderId: '574109052855',
    projectId: 'mypfe-9ed9e',
    storageBucket: 'mypfe-9ed9e.appspot.com',
    iosClientId: '574109052855-pi1s5ahf2meldglv9g0u9cfnnr29okb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.learn',
  );
}
